# themes/tokyo-night/starship.toml

add_newline     = true
palette         = "tokyo_night"
command_timeout = 800

format = """
$directory\
$git_branch\
$git_status\
$git_state\
$python\
$nodejs\
$rust\
$golang\
$docker_context\
$kubernetes\
$status\
$cmd_duration\
$jobs\
$line_break\
$character"""

right_format = """$hostname"""

[palettes.tokyo_night]
bg       = "#1a1b26"
bg_alt   = "#24283b"
fg       = "#c0caf5"
muted    = "#565f89"
red      = "#f7768e"
peach    = "#ff9e64"
yellow   = "#e0af68"
green    = "#9ece6a"
teal     = "#73daca"
sky      = "#7dcfff"
blue     = "#7aa2f7"
mauve    = "#bb9af7"
pink     = "#bb9af7"
sapphire = "#7dcfff"

[character]
success_symbol = "[❯](bold blue)"
error_symbol   = "[❯](bold red)"
vimcmd_symbol  = "[❮](bold green)"

[directory]
style             = "bold sky"
truncation_length = 3
truncate_to_repo  = true
read_only         = " 󰌾"
read_only_style   = "red"
format            = "[$path]($style)[$read_only]($read_only_style) "

[directory.substitutions]
"~/dotfiles"  = " dotfiles"
"~/Documents" = " Documents"
"~/Downloads" = " Downloads"
"~/Pictures"  = " Pictures"
"~"           = " "

[git_branch]
symbol = " "
style  = "bold mauve"
format = "[$symbol$branch]($style) "

[git_status]
style      = "bold yellow"
format     = "([\\[$all_status$ahead_behind\\]]($style) )"
modified   = "✱"
staged     = "✓"
deleted    = "✗"
renamed    = "»"
untracked  = "?"
stashed    = "≡"
conflicted = "✘"
ahead      = "⇡${count}"
behind     = "⇣${count}"
diverged   = "⇕⇡${ahead_count}⇣${behind_count}"

[git_state]
style  = "bold red"
format = '([\($state( $progress_current/$progress_total)\)]($style) )'

[status]
disabled       = false
format         = "[$symbol$common_meaning$signal_name$maybe_int]($style) "
style          = "bold red"
symbol         = "✘ "
success_symbol = ""

[cmd_duration]
min_time = 2000
format   = "[ $duration]($style) "
style    = "dimmed yellow"

[jobs]
symbol           = "✦ "
style            = "bold blue"
number_threshold = 1
symbol_threshold = 1

[python]
symbol  = " "
format  = "[$symbol(\\($virtualenv\\) )]($style)"
style   = "yellow"

[nodejs]
symbol       = " "
format       = "[$symbol($version )]($style)"
style        = "green"
detect_files = ["package.json", ".nvmrc"]

[rust]
symbol = " "
format = "[$symbol($version )]($style)"
style  = "red"

[golang]
symbol = " "
format = "[$symbol($version )]($style)"
style  = "sky"

[docker_context]
symbol          = " "
format          = "[$symbol$context]($style) "
style           = "blue"
only_with_files = true

[kubernetes]
disabled = false
symbol   = "󱃾 "
format   = "[$symbol$context( \\($namespace\\))]($style) "
style    = "mauve"

[hostname]
disabled = false
ssh_only = true
format   = "[@$hostname]($style) "
style    = "bold sapphire"

[username]
disabled = true

[time]
disabled = true

[battery]
disabled = true

[memory_usage]
disabled = true

[package]
disabled = true

[shlvl]
disabled = true
