title = "My arch install script."

additional-repositories = ["multilib"]
archinstall-language = "English"

[audio_config]
audio = "pipewire"

bootloader = "Systemd-boot"
config_version = "2.7.1"
debug = false

[disk_config]
config_type = "default_layout"

[[disk_config.device_modifications]]
device = "/dev/nvme0n1"
wipe = true

[[disk_config.device_modifications.partitions]]
boot = true
fs_type = "fat32"
mountpoint = "/boot"
size = { unit = "MiB", value = 512 }
start = { unit = "MiB", value = 1 }
status = "create"
type = "primary"

[[disk_config.device_modifications.partitions]]
btrfs = [
    { compress = false, mountpoint = "/", name = "@", nodatacow = false },
    { compress = false, mountpoint = "/home", name = "@home", nodatacow = false },
    { compress = false, mountpoint = "/var/log", name = "@log", nodatacow = false },
    { compress = false, mountpoint = "/var/cache/pacman/pkg", name = "@pkg", nodatacow = false },
    { compress = false, mountpoint = "/.snapshots", name = "@.snapshots", nodatacow = false }
]
fs_type = "btrfs"
mount_options = ["compress=zstd"]
obj_id = "81b3853e-75e9-41af-8b55-c99bfa84f147"
size = { unit = "B", value = 511571222528 }
start = { unit = "B", value = 537919488 }
status = "create"
type = "primary"

[disk_encryption]
encryption_type = "luks"
partitions = ["81b3853e-75e9-41af-8b55-c99bfa84f147"]

hostname = "archlinux"

kernels = ["linux", "linux-hardened", "linux-lts"]

[locale_config]
kb_layout = "us abnt2"
sys_enc = "UTF-8"
sys_lang = "en_US"

[offline]
no_pkg_lookups = false

ntp = true

packages = [
    "yad",
    ]

services = [
    "NetworkManager",
    "bluetooth",
    "docker",
    "libvirtd",
    "ntp",
    "ssh",
]

parallel_downloads = 10

[profile_config]
gfx_driver = "AMD / ATI (open-source)"
greeter = "sddm"

[profile_config.profile.custom_settings]
[profile_config.profile.custom_settings.Hyprland]
seat_access = "polkit"

[profile_config.profile.custom_settings.Qtile]

[profile_config.profile.custom_settings.Sway]
seat_access = "polkit"

[profile_config.profile.details]
main = "Desktop"
details = ["Hyprland", "Qtile", "Sway"]

script = "guided"
silent = false
skip_ntp = false
skip_version_check = false
swap = false
timezone = "America/Sao_Paulo"
uki = false
version = "2.7.1"

[custom-commands]
commands = [
    "cd /home/devel; git clone https://aur.archlinux.org/paru.git",
    "chown -R devel:devel /home/devel/paru",
    "usermod -aG docker devel",
    "usermod -aG libvirt devel"
]


[owner]
name = "Oornnery"
github = "github.com/oornnery"

