
[arch] # pacman -Syyu

[arch.system]
pacman = ["openssh", "wget", "bluez", "bluez-utils", "blueman", "pulseaudio", "alsa-utils", "alsa-plugins", "pavucontrol", "xdg-user-dirs", "firefox", "unzip", "htop", "git", "wget", "neovim", "neofetch", "obsidian", "discord", "power-profiles-daemon"]
aur = ["broadcom-bt-firmware", "pulseaudio-bluetooth"]

[arch.fonts]
pacman = []
aur = ["ttf-roboto-mono-nerd", "ttf-jetbrains-mono-nerd", "ttf-firacode-nerd"]

[arch.themes]
pacman = ["arc-gtk-theme", "arc-icon-theme", "papirus-icon-theme", "papirus-folders"]
aur = [""]

[arch.i3] # pacman -Syyu
pacman = ["i3-wm", "rofi", "polybar", "picom", "feh", "dunst", "redshift", "lxappearance", "xfce4-settings", "power-profiles-daemon", "lightdm", "lightdm-gtk-greeter"]
aur = ["autotiling-rs-git"]

[arch.games] 
pacman = ["lutris"]
aur = ["heroic-games-launcher-bin", "teamviewer"]

[arch.development]
pacman = ["github-cli", "python3", "python-pipx", "visual-studio-code-bin", "microsoft-edge-dev-bin", "astronvim"]
aur = ["kabmat"]

[arch.multimedia]
pacman = ["vlc", "mpv"]
aur = ["spotify-adblock-git", "spotify-tui-bin"]

[arch.networking]
pacman = ["networkmanager", "network-manager-applet"]
aur = [""]

[arch.bluetooth]
pacman = []
aur = []

[arch.opcionais]
pacman = ["zsh", "alacritty"]
aur = ["microsoft-edge-bin", "teamviewer", "spotify", "kabmat"]

