[pacman]
unzip
htop
git
alacritty
zsh
wget
neovim
neofetch
python3
python-pipx
obsidian
discord
lutris
power-profiles-daemon
xfce4-settings
github-cli

[AUR/paru]
microsoft-edge-dev-bin
visual-studio-code-bin
teamviewer
mangohud
heroic-games-launcher-bin
kabmat

[i3]
i3-wm
rofi
polybar
picom
feh
dunst
redshift
lxappearance
autotiling-rs-git

[displayManager]
lightdm
lightdm-gtk-greeter

[themes]
arc-gtk-dark
papirus-icon-theme

[fonts]
ttf-roboto-mono-nerd
ttf-jetbrains-mono-nerd
ttf-firacode-nerd

[extra/lutris]
aaa

[pacman/bluetooth]
bluez
bluez-utils
bluez-tools
blueman 

[AUR/paru/bluetooth]
bluez-utils-compat
broadcom-bt-firmware
pulseaudio-bluetooth
