# Active theme: catppuccin-mocha
set -g @dotfiles-theme "catppuccin-mocha"
set -g status-style "bg=default,fg=#6c7086"
set -g status-left "#[fg=#f5c2e7,bold] #S #[default]#{?client_prefix,#[fg=#1e1e2e,bg=#f5c2e7,bold] PREFIX #[default],}#{?pane_synchronized,#[fg=#1e1e2e,bg=#f9e2af,bold] SYNC #[default],}"
set -g status-right "#[fg=#45475a]#H #[fg=#313244]. #[fg=#94e2d5]#{pane_current_command} #[fg=#313244]. #[fg=#cdd6f4]%a %d/%m %H:%M "
setw -g window-status-format "#[fg=#6c7086] #I:#W#{window_flags} "
setw -g window-status-current-format "#[fg=#1e1e2e,bg=#f5c2e7,bold] #I:#W#{window_flags} "
setw -g window-status-activity-style "fg=#f9e2af,bold"
setw -g window-status-bell-style "fg=#f38ba8,bold"
set -g pane-border-style "fg=#313244"
set -g pane-active-border-style "fg=#f5c2e7"
set -g message-style "bg=#f5c2e7,fg=#1e1e2e,bold"
set -g message-command-style "bg=#313244,fg=#cdd6f4"
set -g mode-style "bg=#313244,fg=#cdd6f4"
set -g clock-mode-colour "#f5c2e7"
