# Active theme: catppuccin-mocha
set -g @dotfiles-theme "catppuccin-mocha"
set -g status-style "bg=#1e1e2e,fg=#6c7086"
set -g status-left "#[fg=#1e1e2e,bg=#f5c2e7,bold] #{?pane_in_mode,COPY,#{?client_prefix,PREFIX,#{@dotfiles-zle-mode}}} #[fg=#cdd6f4,bg=#313244,none] #S #[fg=#6c7086,bg=#1e1e2e,none]#{?pane_synchronized,#[fg=#1e1e2e,bg=#f9e2af,bold] SYNC #[fg=#6c7086,bg=#1e1e2e,none],}"
set -g status-right "#[fg=#45475a,bg=#1e1e2e]#H #[fg=#313244,bg=#1e1e2e]. #[fg=#94e2d5,bg=#1e1e2e]#{pane_current_command} #[fg=#313244,bg=#1e1e2e]. #[fg=#cdd6f4,bg=#1e1e2e]%a %d/%m #[fg=#1e1e2e,bg=#f9e2af,bold] %H:%M:%S "
setw -g window-status-format "#[fg=#6c7086,bg=#1e1e2e] #I:#W#{window_flags} "
setw -g window-status-current-format "#[fg=#1e1e2e,bg=#f5c2e7,bold] #I:#W#{window_flags} "
setw -g window-status-activity-style "fg=#f9e2af,bold"
setw -g window-status-bell-style "fg=#f38ba8,bold"
set -g pane-border-style "fg=#313244"
set -g pane-active-border-style "fg=#f5c2e7"
set -g message-style "bg=#f5c2e7,fg=#1e1e2e,bold"
set -g message-command-style "bg=#313244,fg=#cdd6f4"
set -g mode-style "bg=#313244,fg=#cdd6f4"
set -g clock-mode-colour "#f5c2e7"
