# Active theme: gruvbox
set -g @dotfiles-theme "gruvbox"
set -g status-style "bg=default,fg=#928374"
set -g status-left "#[fg=#d79921,bold] #S #[default]#{?client_prefix,#[fg=#282828,bg=#d79921,bold] PREFIX #[default],}#{?pane_synchronized,#[fg=#282828,bg=#fabd2f,bold] SYNC #[default],}"
set -g status-right "#[fg=#504945]#H #[fg=#3c3836]. #[fg=#83a598]#{pane_current_command} #[fg=#3c3836]. #[fg=#ebdbb2]%a %d/%m %H:%M "
setw -g window-status-format "#[fg=#928374] #I:#W#{window_flags} "
setw -g window-status-current-format "#[fg=#282828,bg=#d79921,bold] #I:#W#{window_flags} "
setw -g window-status-activity-style "fg=#fabd2f,bold"
setw -g window-status-bell-style "fg=#fb4934,bold"
set -g pane-border-style "fg=#3c3836"
set -g pane-active-border-style "fg=#d79921"
set -g message-style "bg=#d79921,fg=#282828,bold"
set -g message-command-style "bg=#3c3836,fg=#ebdbb2"
set -g mode-style "bg=#3c3836,fg=#ebdbb2"
set -g clock-mode-colour "#d79921"
