# Active theme: catppuccin-latte
set -g @dotfiles-theme "catppuccin-latte"
set -g status-style "bg=default,fg=#8c8fa1"
set -g status-left "#[fg=#8839ef,bold] #S #[default]#{?client_prefix,#[fg=#eff1f5,bg=#8839ef,bold] PREFIX #[default],}#{?pane_synchronized,#[fg=#eff1f5,bg=#df8e1d,bold] SYNC #[default],}"
set -g status-right "#[fg=#9ca0b0]#H #[fg=#ccd0da]. #[fg=#179299]#{pane_current_command} #[fg=#ccd0da]. #[fg=#4c4f69]%a %d/%m %H:%M "
setw -g window-status-format "#[fg=#8c8fa1] #I:#W#{window_flags} "
setw -g window-status-current-format "#[fg=#eff1f5,bg=#8839ef,bold] #I:#W#{window_flags} "
setw -g window-status-activity-style "fg=#df8e1d,bold"
setw -g window-status-bell-style "fg=#d20f39,bold"
set -g pane-border-style "fg=#ccd0da"
set -g pane-active-border-style "fg=#8839ef"
set -g message-style "bg=#8839ef,fg=#eff1f5,bold"
set -g message-command-style "bg=#ccd0da,fg=#4c4f69"
set -g mode-style "bg=#ccd0da,fg=#4c4f69"
set -g clock-mode-colour "#8839ef"
