
mesa
lib32-mesa
mesa-utils
lib32-mesa-utils

vulkan-intel
lib32-vulkan-intel
vulkan-mesa-layers
lib32-vulkan-mesa-layers
vulkan-virtio
lib32-vulkan-virtio

xf86-input-libinput
xf86-input-synaptics
xf86-input-vmmouse
xf86-video-intel

xorg-xdpyinfo
xorg-server
xorg-xinit
xorg-xinput
xorg-xkill
xorg-xrandr

broadcom-wl-dkms
bluez
bluez-utils

b43-fwcutter

dhclient
dnsmasq
dnsutils
nss-mdns
wpa_supplicant
ethtool
iwd
modemmanager
networkmanager
networkmanager-openconnect
networkmanager-openvpn
xl2tpd
openssh

firewalld

usb_modeswitch

python
python-pip
python-pipx
python-pyqt5
python-pyqt6
python-capng
poetry



pacman-contrib
pkgfile
rebuild-detector

reflector

accountsservice
bash-completion

ffmpegthumbnailer

gst-libav
gst-plugin-pipewire
gst-plugins-bad
gst-plugins-ugly
libdvdcss
libgsf
libopenraw
mlocate
poppler-glib
xdg-user-dirs
xdg-utils
efitools
haveged
nfs-utils
nilfs-utils
ntp
smartmontools
unrar
unzip
xz
adobe-source-han-sans-cn-fonts
adobe-source-han-sans-jp-fonts
adobe-source-han-sans-kr-fonts
cantarell-fonts
freetype2
noto-fonts
ttf-bitstream-vera
ttf-dejavu
ttf-liberation
ttf-opensans
alsa-firmware
alsa-plugins
alsa-utils
pavucontrol
pipewire-pulse
wireplumber
pipewire-alsa
pipewire-jack
rtkit
dmidecode
dmraid
hdparm
hwdetect
lsscsi
mtools
sg3_utils
sof-firmware
power-profiles-daemon
upower
endeavouros-theming
eos-apps-info
eos-log-tool
eos-packagelist
eos-quickstart
eos-rankmirrors
eos-update-notifier
reflector-simple
welcome
duf
findutils
fsarchiver
git
glances
hwinfo
inxi
meld
nano-syntax-highlighting
neofetch
pv
python-defusedxml
python-packaging
rsync
tldr
sed
vi
wget
amd-ucode
intel-ucode
base
base-devel
btrfs-progs
cryptsetup
device-mapper
diffutils
dosfstools
dracut
e2fsprogs
efibootmgr
eos-hooks
endeavouros-keyring
endeavouros-mirrorlist
exfatprogs
f2fs-tools
iptables-nft
inetutils
jfsutils
less
linux
linux-firmware
linux-headers
logrotate
lsb-release
lvm2
man-db
man-pages
mdadm
nano
netctl
ntfs-3g
perl
python
reiserfsprogs
s-nail
sudo
sysfsutils
systemd-sysvcompat
texinfo
usbutils
which
xfsprogs
xterm