# Active theme: kanagawa
set -g @dotfiles-theme "kanagawa"
set -g status-style "bg=#1f1f28,fg=#727169"
set -g status-left "#[fg=#1f1f28,bg=#7e9cd8,bold] #{?pane_in_mode,COPY,#{?client_prefix,PREFIX,#{@dotfiles-zle-mode}}} #[fg=#dcd7ba,bg=#2a2a37,none] #S #[fg=#727169,bg=#1f1f28,none]#{?pane_synchronized,#[fg=#1f1f28,bg=#e6c384,bold] SYNC #[fg=#727169,bg=#1f1f28,none],}"
set -g status-right "#[fg=#54546d,bg=#1f1f28]#H #[fg=#2a2a37,bg=#1f1f28]. #[fg=#98bb6c,bg=#1f1f28]#{pane_current_command} #[fg=#2a2a37,bg=#1f1f28]. #[fg=#dcd7ba,bg=#1f1f28]%a %d/%m #[fg=#1f1f28,bg=#e6c384,bold] %H:%M:%S "
setw -g window-status-format "#[fg=#727169,bg=#1f1f28] #I:#W#{window_flags} "
setw -g window-status-current-format "#[fg=#1f1f28,bg=#7e9cd8,bold] #I:#W#{window_flags} "
setw -g window-status-activity-style "fg=#e6c384,bold"
setw -g window-status-bell-style "fg=#c34043,bold"
set -g pane-border-style "fg=#2a2a37"
set -g pane-active-border-style "fg=#7e9cd8"
set -g message-style "bg=#7e9cd8,fg=#1f1f28,bold"
set -g message-command-style "bg=#2a2a37,fg=#dcd7ba"
set -g mode-style "bg=#2a2a37,fg=#dcd7ba"
set -g clock-mode-colour "#7e9cd8"
