# Active theme: kanagawa
set -g @dotfiles-theme "kanagawa"
set -g status-style "bg=default,fg=#727169"
set -g status-left "#[fg=#7e9cd8,bold] #S #[default]#{?client_prefix,#[fg=#1f1f28,bg=#7e9cd8,bold] PREFIX #[default],}#{?pane_synchronized,#[fg=#1f1f28,bg=#e6c384,bold] SYNC #[default],}"
set -g status-right "#[fg=#54546d]#H #[fg=#2a2a37]. #[fg=#98bb6c]#{pane_current_command} #[fg=#2a2a37]. #[fg=#dcd7ba]%a %d/%m %H:%M "
setw -g window-status-format "#[fg=#727169] #I:#W#{window_flags} "
setw -g window-status-current-format "#[fg=#1f1f28,bg=#7e9cd8,bold] #I:#W#{window_flags} "
setw -g window-status-activity-style "fg=#e6c384,bold"
setw -g window-status-bell-style "fg=#c34043,bold"
set -g pane-border-style "fg=#2a2a37"
set -g pane-active-border-style "fg=#7e9cd8"
set -g message-style "bg=#7e9cd8,fg=#1f1f28,bold"
set -g message-command-style "bg=#2a2a37,fg=#dcd7ba"
set -g mode-style "bg=#2a2a37,fg=#dcd7ba"
set -g clock-mode-colour "#7e9cd8"
