# btop/.config/btop/btop.conf
# Stowed + overwritten by `dots theme set`.

color_theme = "catppuccin-mocha"
theme_background = true
truecolor = true
force_tty = false

# Graph scaling
graph_symbol = "block"
graph_lines = "auto"

# Boxes shown (order matters)
shown_boxes = "cpu:proc:mem:net"

# Process options
proc_sorting = "cpu direct"
proc_filter = ""
proc_gradient = true
proc_per_core = true
proc_reversed = false
proc_tree = false
proc_depth = 2

# CPU
cpu_sensor = "Auto"
show_coretemp = true
cpu_graph = "combined"
cpu_sync = true

# Memory
mem_below_net = false
swap_disk = true
show_swap = true
swap_below_net = true

# Network
net_iface = "auto"
net_sync = false
net_download = 100
net_upload = 100

# Temp symbols
temp_symbol = "cpu"

# Display
update_ms = 2000
rounded_corners = true
vim_keys = false
