admin_mode:
  enabled: true

restore_point:
  enabled: true

bitlocker:
  mount_point: "C:"
  encryption_method: "Aes256"
  used_space_only: true
  skip_hardware_test: true

firewall:
  enabled: true
  profiles:
    - Domain
    - Public
    - Private

network:
  discovery: "Private"
  file_sharing: false
  ipv6: false
  dns:
    interface_index: 0
    addresses:
      - "1.1.1.1"
      - "1.0.0.1"

windows_update:
  enable: true

windows_defender:
  enable: true

bloatware:
  apps_to_remove:
    # - "Microsoft.Xbox.TCUI"
    # - "Microsoft.XboxApp"
    # - "Microsoft.XboxGameOverlay"
    # - "Microsoft.XboxGamingOverlay"
    # - "Microsoft.XboxIdentityProvider"
    # - "Microsoft.XboxSpeechToTextOverlay"
    # - "Microsoft.GamingApp"                    # Modern Xbox Gaming App, required for installing some PC games
    - "Microsoft.OutlookForWindows"              # New mail app: Outlook for Windows
    - "Microsoft.People"                         # Required for & included with Mail & Calendar
    - "Microsoft.PowerAutomateDesktop"
    - "Microsoft.RemoteDesktop"
    - "Microsoft.Windows.DevHome"
    - "Microsoft.windowscommunicationsapps"      # Mail & Calendar
    # - "Microsoft.Copilot"                      # New Windows Copilot app
    # - "Microsoft.Edge"                         # Edge browser (Can only be uninstalled in European Economic Area)
    # - "Microsoft.GetHelp"                      # Required for some Windows 11 Troubleshooters
    - "Microsoft.MSPaint"                        # Paint 3D
    - "Microsoft.OneDrive"                       # OneDrive consumer
    # - "Microsoft.Paint"                        # Classic Paint
    # - "Microsoft.ScreenSketch"                 # Snipping Tool
    # - "Microsoft.Whiteboard"                   # Only preinstalled on devices with touchscreen and/or pen support
    # - "Microsoft.Windows.Photos"
    # - "Microsoft.WindowsCalculator"
    # - "Microsoft.WindowsCamera"
    # - "Microsoft.WindowsNotepad"
    # - "Microsoft.WindowsStore"                 # Microsoft Store, WARNING: This app cannot be reinstalled!
    # - "Microsoft.WindowsTerminal"              # New default terminal app in windows 11
    - "Microsoft.YourPhone"                      # Phone link
    - "MicrosoftWindows.CrossDevice"             # Phone integration within File Explorer, Camera and more
    - "Microsoft.ZuneMusic"
    - "Microsoft.ZuneVideo"
    - "Microsoft.BingSearch"
    - "Clipchamp.Clipchamp"
    - "Microsoft.3DBuilder"
    - "Microsoft.549981C3F5F10"                  # Cortana app
    - "Microsoft.BingFinance"
    - "Microsoft.BingFoodAndDrink"            
    - "Microsoft.BingHealthAndFitness"         
    - "Microsoft.BingNews"
    - "Microsoft.BingSports"
    - "Microsoft.BingTranslator"
    - "Microsoft.BingTravel" 
    - "Microsoft.BingWeather"
    - "Microsoft.Getstarted"                    # Cannot be uninstalled in Windows 11
    - "Microsoft.Messaging"
    - "Microsoft.Microsoft3DViewer"
    - "Microsoft.MicrosoftJournal"
    - "Microsoft.MicrosoftOfficeHub"
    - "Microsoft.MicrosoftPowerBIForWindows"
    - "Microsoft.MicrosoftSolitaireCollection"
    - "Microsoft.MicrosoftStickyNotes"
    - "Microsoft.MixedReality.Portal"
    - "Microsoft.NetworkSpeedTest"
    - "Microsoft.News"
    - "Microsoft.Office.OneNote"
    - "Microsoft.Office.Sway"
    - "Microsoft.OneConnect"
    - "Microsoft.Print3D"
    - "Microsoft.SkypeApp"
    - "Microsoft.Todos"
    - "Microsoft.WindowsAlarms"
    - "Microsoft.WindowsFeedbackHub"
    - "Microsoft.WindowsMaps"
    - "Microsoft.WindowsSoundRecorder"
    - "Microsoft.ZuneVideo"
    - "MicrosoftCorporationII.MicrosoftFamily"   # Family Safety App
    - "MicrosoftCorporationII.QuickAssist"
    - "MicrosoftTeams"   # Old MS Teams personal (MS Store)
    - "MSTeams"   # New MS Teams app
    - "ACGMediaPlayer"
    - "ActiproSoftwareLLC"
    - "AdobeSystemsIncorporated.AdobePhotoshopExpress"
    - "Amazon.com.Amazon"
    - "AmazonVideo.PrimeVideo"
    - "Asphalt8Airborne" 
    - "AutodeskSketchBook"
    - "CaesarsSlotsFreeCasino"
    - "COOKINGFEVER"
    - "CyberLinkMediaSuiteEssentials"
    - "DisneyMagicKingdoms"
    - "Disney"
    - "DrawboardPDF"
    - "Duolingo-LearnLanguagesforFree"
    - "EclipseManager"
    - "Facebook"
    - "FarmVille2CountryEscape"
    - "fitbit"
    - "Flipboard"
    - "HiddenCity"
    - "HULULLC.HULUPLUS"
    - "iHeartRadio"
    - "Instagram"
    - "king.com.BubbleWitch3Saga"
    - "king.com.CandyCrushSaga"
    - "king.com.CandyCrushSodaSaga"
    - "LinkedInforWindows"
    - "MarchofEmpires"
    - "Netflix"
    - "NYTCrossword"
    - "OneCalendar"
    - "PandoraMediaInc"
    - "PhototasticCollage"
    - "PicsArt-PhotoStudio"
    - "Plex"
    - "PolarrPhotoEditorAcademicEdition"
    - "Royal Revolt"
    - "Shazam"
    - "Sidia.LiveWallpaper"
    - "SlingTV"
    - "Spotify"
    - "TikTok"
    - "TuneInRadio"
    - "Twitter"
    - "Viber"
    - "WinZipUniversal"
    - "Wunderlist"
    - "XING"

services:
  services_to_disable:
    - "DiagTrack"
    - "dmwappushservice"
    - "HomeGroupListener"
    - "HomeGroupProvider"
    - "lfsvc"
    - "MapsBroker"
    - "NetTcpPortSharing"
    - "RemoteAccess"
    - "RemoteRegistry"
    - "SharedAccess"
    - "TrkWks"
    - "WbioSrvc"
    - "WMPNetworkSvc"
    - "XblAuthManager"
    - "XblGameSave"

visual_effect:
  performance: true

power_plan:
  hibernation: true
  monitor_timeout_ac: 10
  monitor_timeout_dc: 5
  standby_timeout_ac: 0
  standby_timeout_dc: 15

storage:
  disable_indexing_for_ssd: true

privacy:
  adivertising_id:
    enable: false
  tailored_experiences:
    enable: false
  telemetry:
    enabled: false

optional_features:
  features_to_disable:
    - "Internet-Explorer-Optional-amd64"
    - "WorkFolders-Client"
  features_to_enable:
    - "Microsoft-Windows-Subsystem-Linux"
    - "VirtualMachinePlatform"


winget:
  apps:
    - "Microsoft.PowerAutomate"
    - "Microsoft.PowerToys"
    - "Microsoft.WindowsTerminal"
    - "Microsoft.WSL"
    - "Debian.Debian"
    - "7zip.7zip"
    - "ShareX.ShareX"
    - "Audacity.Audacity"
    - "GIMP.GIMP"
    - "Docker.DockerDesktop"
    - "Git.Git"
    - "GitHub.cli"
    - "GitHub.GitHubDesktop"
    - "WireGuard.WireGuard"
    - "VideoLAN.VLC"
    - "calibre.calibre"
    - "Hashicorp.Vagrant"
    - "Neovim.Neovim"
    - "TheDocumentFoundation.LibreOffice"
    - "Notion.Notion"
    - "Notion.NotionCalendar"
    - "MarkText.MarkText"
    - "Obsidian.Obsidian"
    - "Anki.Anki"
    - "WiresharkFoundation.Wireshark"
    - "VSCodium.VSCodium"
    - "Microsoft.VisualStudioCode"
    - "Microsoft.PowerShell"
    - "Oracle.VirtualBox"
    - "Starship.Starship"
    - "AnyDeskSoftwareGmbH.AnyDesk"
    - "Brave.Brave"
    - "Vivaldi.Vivaldi"
    - "OBSProject.OBSStudio"
    - "RamenSoftware.Windhawk"
    - "qBittorrent.qBittorrent"
    - "Mojang.MinecraftLauncher"
    - "EpicGames.EpicGamesLauncher"
    - "ElectronicArts.EADesktop"
    - "Valve.Steam"
    - "Blitz.Blitz"
    - "Overwolf.CurseForge"
    - "Discord.Discord"
    - "Python.Python.3.12"
    - "astral-sh.ruff"
    - "astral-sh.uv"
    - "Ollama.Ollama"
    - "9P8LTPGCBZXD" # Wintoys

wsl:
  enabled: true
  distribution: "Debian"
  # config:
  #   memory: "6GB"
  #   processors: 2
  #   swap: 0
  #   gui_applications: true
  #   dns_proxy: true
  #   networking_mode: "NAT"
  #   firewall: true
  #   sparse_vhd: false
  #   auto_memory_reclaim: "disabled"
  #   kernel_path: "C:\\Users\\user\\Downloads\\kernel"

temp_files:
  clear: true
