# Active theme: nord
set -g @dotfiles-theme "nord"
set -g status-style "bg=default,fg=#4c566a"
set -g status-left "#[fg=#88c0d0,bold] #S #[default]#{?client_prefix,#[fg=#2e3440,bg=#88c0d0,bold] PREFIX #[default],}#{?pane_synchronized,#[fg=#2e3440,bg=#ebcb8b,bold] SYNC #[default],}"
set -g status-right "#[fg=#434c5e]#H #[fg=#3b4252]. #[fg=#81a1c1]#{pane_current_command} #[fg=#3b4252]. #[fg=#d8dee9]%a %d/%m %H:%M "
setw -g window-status-format "#[fg=#4c566a] #I:#W#{window_flags} "
setw -g window-status-current-format "#[fg=#2e3440,bg=#88c0d0,bold] #I:#W#{window_flags} "
setw -g window-status-activity-style "fg=#ebcb8b,bold"
setw -g window-status-bell-style "fg=#bf616a,bold"
set -g pane-border-style "fg=#3b4252"
set -g pane-active-border-style "fg=#88c0d0"
set -g message-style "bg=#88c0d0,fg=#2e3440,bold"
set -g message-command-style "bg=#3b4252,fg=#d8dee9"
set -g mode-style "bg=#3b4252,fg=#d8dee9"
set -g clock-mode-colour "#88c0d0"
