config:
  backup: true
  banner: true
  create: true
  dotpath: dotfiles
  ignoreempty: false
  keepdot: false
  longkey: false
  showdiff: false
  workdir: ~/.config/dotdrop
dotfiles:
  bash_rc:
    src: .bashrc
    dst: ~/.bashrc
  bash_profile:
    src: .bash_profile
    dst: ~/.bash_profile
  zshrc:
    src: .zshrc
    dst: ~/.zshrc
  zsh_profile:
    src: .zprofile
    dst: ~/.zprofile
  vimrc:
    src: .vimrc
    dst: ~/.vimrc
  gitconfig:
    src: .gitconfig
    dst: ~/.gitconfig
  gitignore_global:
    src: .gitignore_global
    dst: ~/.gitignore_global
  code_profile:
    src: .vscode/settings.json
    dst: ~/.config/Code/User/settings.json
  wallpapers:
    src: .wallpapers
    dst: ~/.wallpapers
  scripts:
    src: .scripts
    dst: ~/.scripts
  screenlayout:
    src: .screenlayout
    dst: ~/.screenlayout
  lightdm:
    # TODO: Ler doc disso
    src: lightdm
    dst: ~/.config/lightdm
  alacritty:
    src: .config/alacritty
    dst: ~/.config/alacritty
  autorandr:
    src: .config/autorandr
    dst: ~/.config/autorandr
  dunst:
    src: .config/dunst
    dst: ~/.config/dunst
  htop:
    src: .config/htop
    dst: ~/.config/htop
  hypr:
    src: .config/hypr
    dst: ~/.config/hypr
  i3:
    src: .config/i3
    dst: ~/.config/i3
  nvim:
    src: .config/nvim
    dst: ~/.config/nvim
  picom:
    src: .config/picom
    dst: ~/.config/picom
  qtile:
    src: .config/qtile
    dst: ~/.config/qtile
  redshift:
    src: .config/redshift
    dst: ~/.config/redshift
  rofi:
    src: .config/rofi
    dst: ~/.config/rofi
  sway:
    src: .config/sway
    dst: ~/.config/sway
    # TODO: add action to install sway
  swaylock:
    src: .config/swaylock
    dst: ~/.config/swaylock
  swaync:
    src: .config/swaync
    dst: ~/.config/swaync
  waybar:
    src: .config/waybar
    dst: ~/.config/waybar
  wofi:
    src: .config/wofi
    dst: ~/.config/wofi
  # TODO: Add awesomewm
actions:
  zsh_plugins: 'my-dotfiles/scripts/zsh_plugins.sh'
  sway_wm: 'my-dotfiles/scripts/sway_wm.sh'
profiles:
  full_home_sway:
    actions:
      - zshrc
      - zsh_profile
      - vimrc
      - gitconfig
      - gitignore_global
      - code_profile
      - wallpapers
      - scripts
      - screenlayout
      - alacritty
      - autorandr
      - htop
      - nvim
      - redshift
      - sway
      - swaylock
      - swaync
      - waybar
      - wofi